config/routes.rb
Rails.application.routes.draw do
  resources :ekneks

  get '/register', to: 'users#new'
  resources :users, only: [:create]

  get '/sign_in', to: 'sessions#new'
  get 'sign_out', to: 'sessions#destroy'
  resource :sessions, only: [:create]
  
  get 'dashboard/home'
  root 'sessions#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/eknek.rb
class Eknek < ApplicationRecord
    has_one_attached :file
    # validates_with AttachmentSizeValidator, attributes: :file, less_than: 1.gigabytes 
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

    validates :password, length: { minimum: 6, allow_nil: true }
    validates :email, presence: true, uniqueness: true
    has_many :ekneks
    
    def password
        @password
    end

    def password=(raw)
        @password = raw
        self.password_digest = BCrypt::Password.create(raw)
    end
    def is_password?(raw)
        BCrypt::Password.new(password_digest).is_password?(raw)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

helper_method :current_user

def ensure_current_user
    if current_user.nil?
        redirect_to sign_in_path
    end
end

    def current_user
        if session[:user_id]
            User.find(session[:user_id])
        end
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :ensure_current_user
  def index
  end
  def show
  end
end

app/controllers/ekneks_controller.rb
class EkneksController < ApplicationController
  before_action :set_eknek, only: %i[ show edit update destroy ]
  before_action :ensure_current_user
  # GET /ekneks or /ekneks.json
  def index
    @ekneks = current_user.ekneks
  end

  # GET /ekneks/1 or /ekneks/1.json
  def show
  end

  # GET /ekneks/new
  def new
    @eknek = Eknek.new
  end

  # GET /ekneks/1/edit
  def edit
  end

  # POST /ekneks or /ekneks.json
  def create
    @eknek = current_user.ekneks.new(eknek_params)

    respond_to do |format|
      if @eknek.save
        format.html { redirect_to eknek_url(@eknek), notice: "Eknek was successfully created." }
        format.json { render :show, status: :created, location: @eknek }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @eknek.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ekneks/1 or /ekneks/1.json
  def update
    respond_to do |format|
      if @eknek.update(eknek_params)
        format.html { redirect_to eknek_url(@eknek), notice: "Eknek was successfully updated." }
        format.json { render :show, status: :ok, location: @eknek }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @eknek.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ekneks/1 or /ekneks/1.json
  def destroy
    @eknek.destroy

    respond_to do |format|
      format.html { redirect_to ekneks_url, notice: "Eknek was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eknek
      @eknek = current_user.ekneks.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def eknek_params
      params.require(:eknek).permit(:title, :description, :file)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # lookup the user in the database
    @user = User.find_by(email: user_params[:email])

    if @user && @user.is_password?(user_params[:password])
      session[:user_id] = @user.id
      redirect_to dashboard_home_path
    else
      flash.now[:notice] = "Invalid email or password"
      render :new
    # Compare their password to the password they entered
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to sign_in_path
  end 

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to sign_in_path
    else
      flash.now[:notice] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

private

def user_params
  params.require(:user).permit(:name, :email, :password)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/ekneks_helper.rb
module EkneksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/home.html.erb
<div class="dashboard-top col-md-11 mx-auto p-3 mb-4 d-flex justify-content-between" style="background-color: rgba(0, 0, 0, 0.2);">
   <h6>HOME</h6>  
</div>

<div class="container">
  <h2>Assignment statement:</h2>
  <p>We need to design a system allowing verified users to upload sensitive data in the form of large files. To this end, we'd want to do the flilowing:</p>
  <ol>
    <li>As a user, I should be able to login on the platform using email address and password.</li>
    <li>As a logged-in user, I should be able to see a list of all the files that I have uploaded. This list should be private and not visible to other users on the platform or to external parties.</li>
    <li>As a logged-in user, I should be able to delete an already uploaded file.</li>
    <li>As a logged-in user, I should be able to upload a new file while specifying some additional info such as a title, description, etc. Once uploaded, the platform should figure out the file type and optionally compress it for storage. The file size could be anything upto 1GB.</li>
    <li>As a logged-in user, I should be able to share one of my files publicly using a tiny URL obtained from the system.</li>
  </ol>         
 </div>

app/views/ekneks/_eknek.html.erb
<div id="<%= dom_id eknek %>">
  <p>
    <strong>Title:</strong>
    <%= eknek.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= eknek.description %>
  </p>

</div>

app/views/ekneks/_form.html.erb
<div class="col-md-8 mx-auto">
<%= form_with(model: eknek) do |form| %>
  <% if eknek.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(eknek.errors.count, "error") %> prohibited this eknek from being saved:</h2>

      <ul>
        <% eknek.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-outline mb-4">
    <%= form.text_field :title, class: "form-control" %>
    <label class="form-label" for="Name">Title</label>
  </div>

  <div>
    <%= form.text_area :description, class: "form-control" %>
    <label class="form-label" for="description">Description</label>
  </div>

  <div>

    <%= form.file_field :file, class:"form-control-file mb-3 mt-3" %>
  </div>

  <div>
    <%= form.submit "Create File", class: "btn btn-primary"%>
  </div>
<% end %>
</div>

app/views/ekneks/edit.html.erb
<h1>Editing eknek</h1>

<%= render "form", eknek: @eknek %>

<br>

<div>
  <%= link_to "Show this eknek", @eknek %> |
  <%= link_to "Back to ekneks", ekneks_path %>
</div>

app/views/ekneks/index.html.erb
<div class="col-md-10 mx-auto">
<p style="color: green"><%= notice %></p>
<%= link_to "Create New File", new_eknek_path, :class => "btn btn-primary mb-3" %>
<table class="table table-hover table-bordered table-sm">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>URL</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
  <% @ekneks.each do |eknek| %>
      <tr>
        <td><%= eknek.title %></td>
        <td><%= eknek.description %></td>
        <td><%= link_to "Copy", eknek, :class => "btn btn-primary" %></td>
        <td><%= link_to "View", eknek, :class => "btn btn-primary" %></td>
        <td><%= link_to "Edit", edit_eknek_path(eknek), :class => "btn btn-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/ekneks/new.html.erb
<h1 class="text-center">Create New File</h1>

<%= render "form", eknek: @eknek %>

<br>

<div class"col-md-12">
  <%= link_to "Back to Files", ekneks_path, class: "btn btn-secondary" %>
</div>

app/views/ekneks/show.html.erb
<div class="mx-auto col-md-8">
<p style="color: green"><%= notice %></p>
<%= render @eknek %>
<div>

  <%= link_to "Edit Description", edit_eknek_path(@eknek), :class => "btn btn-secondary mb-3" %> |
  <%= link_to "Back to Files", ekneks_path, :class => "btn btn-secondary"  %> |
  <%= link_to "Download file", @eknek.file, download: '', :class => "btn btn-primary" %>
  <%= button_to "Destroy this File", @eknek, method: :delete, :class => "btn btn-danger" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filesharing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <p class="nav-link active" aria-current="page" ><%= link_to "Home", dashboard_home_path, :class => "btn btn-primary" %></p>
            </li>
            <li class="nav-item">
              <p class="nav-link" ><%= link_to "Add New File", new_eknek_path, :class => "btn btn-primary" %></p>
            </li>
            <li class="nav-item">
            <p class="nav-link" ><%= link_to "View Files", ekneks_path, :class => "btn btn-primary" %></p>
          </li>
          </ul>
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <% if current_user %>
                Hello <%= current_user.name %>
                <% end %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item cursor-pointer">
                <%= link_to "Log Out", sign_out_path %></li>
              </ul>
            </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</html>

app/views/users/new.html.erb
<section class="mt-3" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>

                <form action="/users" class="mx-1 mx-md-4" method="post">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

                  <div class="d-flex flex-row align-items-center mb-4">
                  <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                  <div class="form-outline flex-fill mb-0">
                    <input type="name" id="name" name="user[name]" class="form-control" value="<%= @user.name %>" />
                    <label class="form-label" for="name">Username</label>
                  </div>
                </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input class="form-control" type="email" id="email" name="user[email]" value="<%= @user.email %>" />
                      <label class="form-label" for="email">Your Email</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="password" id="password" name="user[password]" class="form-control" />
                      <label class="form-label" for="password">Password</label>
                    </div>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <p>Have Account Already? <%= link_to "Sign In", sign_in_path %></p>
                  </div>
               

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" value="Register" class="btn btn-primary btn-lg">Register</button>
                  </div>
                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp" class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>